# Generated by Django 5.2 on 2025-05-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Musician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fist_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("birth", models.DateField()),
            ],
        ),
    ]
