# Generated by Django 5.2 on 2025-05-05 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bands", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="musician",
            old_name="fist_name",
            new_name="first_name",
        ),
    ]
